BDP         = Magic Header *Entry

Magic       = %s"BDP"
Header      = %x44

Entry       = NameEntry ValueEntry

NameEntry   = NameLength Name
ValueEntry  = ValueLength Value

NameLength  = 4(%x00-FF)
Name        = *(%x00-FF)

ValueLength = 4(%x00-FF)
Value       = *(%x00-FF)