BDP         = Magic Header *Entry

Magic       = %s"BDP"
Header      = %x12

Entry       = NameEntry ValueEntry

NameEntry   = NameLength Name
ValueEntry  = ValueLength Value

NameLength  = 1(%x00-FF)
Name        = *(%x00-FF)

ValueLength = 2(%x00-FF)
Value       = *(%x00-FF)